services:
  mysportapp:
    build: .
    networks:
      - back-end
    ports:
      - 8088:8080
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mysportapp
    networks:
      - back-end
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - back-end
    ports:
      - 8081:8080

networks:
  front-end:
    name: mysportapp-fe
  back-end:
    name: mysportapp-be